--- #YAML:1.0
name:               SQL-QueryBuilder-OO
version:            0.1
abstract:           Object oriented SQL query builder
author:
    - Oliver Schieche <schiecheo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Params::Validate:  0
    perl:              5.010
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
